name: Trigger Fw-docs workflow for Deploy Vivally Documentation

on:
  push:
    branches:
      - Sid-develop
jobs:
  trigger-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Doxygen Documentation Build
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/vivally/fw-docs/dispatches \
          -d '{"event_type": "generate-docs"}'
